// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytvhjcqqclgouytqdhat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0dmhqY3FxY2xnb3V5dHFkaGF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4OTEwNDIsImV4cCI6MjA2MzQ2NzA0Mn0.mwslV5LW4su7htP2_YywSBTLbsQE_ZgcmxUn-m26O_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);